### ISSUE TITLE
Ability to escape delimiters and new line within data

### ISSUE THREAD

**Issue by anandsiva** [CommBank/maestro#436]
Extracts should be able to provide a way for escaping delimiters so that the delimiter itself becomes part of the data and is retained as is. In terms of line Feed if linefeed is a part of the data the maestro should be able to treat it as part of data. Both the delimiter and line feed should also be passed as part of the data on to Teradata

**Comment by anandsiva** [comment]
This is applicable both for file based ingestion and databased pull. In case of file based extract we need to provide the source on the escape char.
When the data is pulled the escaping should be part of the extract query itself.

**Comment by stephanh** [comment]
What particular file format standard do we need to support? Is https://tools.ietf.org/html/rfc4180 enough?

**Comment by anandsiva** [comment]
We define the the format and standards. The requirement was more around handling the both delimiter and line feed so that we load them on to the hive table and also to be able to pass them as is on to teradata.

**Comment by stephanh** [comment]
I will have to investigate if Sqoop allows you to escape the end of line character.

**Comment by stephanh** [comment]
*Hive shouldn't be a problem since the data will be stored in Parquet so delimiters won't matter.
* For file ingest we will have to write a custom file input format, maybe on top of https://github.com/tresata/cascading-opencsv/blob/master/src/main/java/com/tresata/cascading/opencsv/OpenCsvScheme.java
* Not sure what we need to do for text export. We might need a custom output file output format to ensure that we don't get output counters that are off.

**Comment by anandsiva** [comment]
The immediate requirement is to solve it for sqoop import and sqoop export to Teradata.

**Comment by SamRoberts** [comment]
What part of this does the existing opencsv based splitter not already support? Escaping delimters is not problem, iirc. Not sure about escaping newlines, but I would expect opencsv to handle that if you were able to hand the splitter a line that contained a LF.

**Comment by stephanh** [comment]
@SamRoberts do you mean the splitter in Maestro or the OpenCsvScheme I linked to?

The Maestro splitter can't handle newline characters because the standard FileInputFormat splits lines based on the newline character so it would break up lines where the delimter is escaped.

**Comment by stephanh** [comment]
@anandsiva we would have to run tests against sqoop to see what it actually supports.

**Comment by SamRoberts** [comment]
@stephanh Yes, but the newline character is the only outstanding requirement here, iirc. But reviewing your comments, you knew that already ... so ... yeah, that's my useful contribution. :)

**Comment by stephanh** [comment]
@SamRoberts it also happens to be the most involved requirement :smile:.

@anandsiva if I understand you correctly than we only have to address this issue for DB import and exports. File based loads can remain as they are? Is that correct?

**Comment by anandsiva** [comment]
The current requirement is the use-case you mentioned. All file would would stick to the existing standards unless they have a pressing need to handle delimited within the data. The solution and approach we are taking should solve this for both file import and DB import and sqoop export as well.

**Comment by stephanh** [comment]
For DB imports we are considering adding the ability to import/export to/form Parquet. This will solve any delimiter problems. However, this does not solve the problem for files. That would be a different solution.

**Comment by stephanh** [comment]
I estimate that doing the importing/exporting to/from parquet and integrating that into Maestro will be about 2 sprints for an initial solution.

**Comment by anandsiva** [comment]
Similarly do you have a proposed solution for file based imports as well. This solution will not be a norm as it will have Performance implications and would be used on loads which ever allows free text in the source.

**Comment by stephanh** [comment]
For file based loads we will need to use the OpenCSVScheme or reimplement our own. This will probably take 2 sprints as well.
